---
kind: pipeline
name: default

clone:
  depth: 50

steps:
  - name: eslint
    image: marcbachmann/eslint:9.1.1
    when: {event: [push]}
    depends_on: []
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN


- name: install
  image: node:24-alpine
  commands: ["npm ci"]

- name: test-node-22
  image: node:22-alpine
  commands: ["npm run test -s"]

- name: test-node-24
  image: node:24-alpine
  commands: ["npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v3.0.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
    NPM_TOKEN:
      from_secret: NPM_TOKEN

trigger:
  event: [push]
